## Heartbeat configuration
## https://github.com/elastic/beats/blob/main/deploy/docker/heartbeat.docker.yml
#

heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - https://elasticsearch:9200
  username: elastic
  password: ${ELASTIC_PASSWORD}
  ssl:
    certificate_authorities: ['${path.home}/elasticsearch-ca.pem']

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: ['https://elasticsearch:9200']
  username: elastic
  password: ${ELASTIC_PASSWORD}
  ssl:
    certificate_authorities: ['${path.home}/elasticsearch-ca.pem']

## HTTP endpoint for health checking
## https://www.elastic.co/guide/en/beats/heartbeat/current/http-endpoint.html
#

http.enabled: true
http.host: 0.0.0.0
