# This is the main Search Guard configuration file where authentication
# and authorization is defined.
#
# See
#  - https://docs.search-guard.com/latest/authentication-authorization
#  - https://git.floragunn.com/search-guard/search-guard/-/blob/master/sgconfig/sg_config.yml

_sg_meta:
  type: config
  config_version: 2

# This demo configuration enables a single authentication domain for both
# HTTP/REST and transport layers, with HTTP basic authentication enabled using
# the internal user database module (users are defined in sg_internal_users.yml).

sg_config:
  dynamic:
    authc:
      basic_internal_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal
