# Search Guard uses role mappings to determine which Search Guard roles should
# be assigned to the user after authentication. Users and backend roles are
# defined in sg_internal_users.yml.
#
# See
#  - https://docs.search-guard.com/latest/mapping-users-roles
#  - https://git.floragunn.com/search-guard/search-guard/-/blob/master/sgconfig/sg_roles_mapping.yml

_sg_meta:
  type: rolesmapping
  config_version: 2

## Demo roles mappings
#

SGS_ALL_ACCESS:
  reserved: true
  backend_roles:
    - admin

SGS_LOGSTASH:
  backend_roles:
    - logstash

SGS_KIBANA_SERVER:
  reserved: true
  users:
    - kibanaserver

SGS_KIBANA_USER:
  backend_roles:
    - kibanauser

SGS_READALL:
  reserved: true
  backend_roles:
    - readall

SGS_MANAGE_SNAPSHOTS:
  reserved: true
  backend_roles:
    - snapshotrestore

SGS_OWN_INDEX:
  users:
    - '*'
